### ISSUE TITLE
Please create requirements.txt

### ISSUE THREAD

**Issue by interduo** [n-st/birdwatch#5]
It's very common to create requirements.txt for easy installing python3 requirements like:
`pip install -r requirements.txt`

**Comment by n-st** [comment]
To be frank I haven't actively used birdwatch in a long time (that's also why it's unchanged since 2019)…
If I'm not mistaken, it relies only on the Python standard library. I'll add an empty requirements.txt to signify that.

**Comment by n-st** [comment]
20065a5
